### ISSUE TITLE
Add Initial Documentation

### ISSUE THREAD

**Issue by oswalpalash** [oswalpalash/AndroidLiquid#1]
Add basic documentation about the project

ie : Project built on jBox2D
It is an alternative to Liquidfun built by google.

**Comment by iamdharmveer** [comment]
Check out added a README.md file for documentation 👍

**Comment by oswalpalash** [comment]
@iamdharmveer This is an android project. Not a Gem module. Pls update.

**Comment by iamdharmveer** [comment]
Okay. 👍

**Comment by iamdharmveer** [comment]
But please give details about your project so I can add them in documentation part .

**Comment by oswalpalash** [comment]
Liquid Simulation in Java using physics engine (box2d) and designing a portable API for easier usage. The project is open sourced and built from scratch on Java platform using Android Studio and gradle.

**Comment by iamdharmveer** [comment]
Now It is complete as you  give the  details .
