### ISSUE TITLE
Create a video of the APK in game

### ISSUE THREAD

**Issue by oswalpalash** [oswalpalash/AndroidLiquid#12]
Create the screen cast video of the APK and attach it to README.

**Comment by raj-subhankar** [comment]
You want a video or a gif? I don't think Github supports video playback.

**Comment by kingroryg** [comment]
GIF would be a better option .

**Comment by oswalpalash** [comment]
@saru95 Alrighty. @raj-subhankar We can go with a GIF.. My initial plan was to link it to youtube and embed here. A high quality GIF would be good.

**Comment by raj-subhankar** [comment]
We can do youtube video, but then owner has to upload the video and update in README.

**Comment by oswalpalash** [comment]
@raj-subhankar First lets get it added to repo. Maybe that can be done later.
