### ISSUE TITLE
Add Opensource License

### ISSUE THREAD

**Issue by oswalpalash** [oswalpalash/AndroidLiquid#7]
need to draft and write up a license for this project.

**Comment by yvsja** [comment]
Please assign me this issue.
What license do you want to be added MIT, Apache 2.0 or any other?

**Comment by oswalpalash** [comment]
MIT License would be relevant I guess.

**Comment by yvsja** [comment]
Ok. I am on it!

**Comment by oswalpalash** [comment]
@yvsja 👍
